### PR TITLE
Enhance the download instructions a bit

### PR DESCRIPTION
**Pull request by marcjansen**
This enhances the instructions to download a matching jar file. It might not be self-explanatory for everyone.

Peek 2023-05-11 19-03

Please review @geostyler/sprinters

### CODE REVIEW

**Review by jansule — COMMENTED** [review]
That's fantastic! :rocket: While seeing your GIF, how about adding a GIF that shows how to actually download a jar?

**Comment by marcjansen** [comment]
Thank for the review. I added a gif, and also fixed sth. you missed in your review.

You wanna take another peek?

**Review by jansule — APPROVED** [review]
I'm speechless :1st_place_medal:

**Pull request merged**
